name: Test building container image for azure-pipelines-centos7
on:
  push:
    paths:
      - 'centos7/*'
  pull_request:
    paths:
      - 'centos7/*'


jobs:
  build:
    name: Build image for azure-pipelines-centos7
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      uses: redhat-actions/buildah-build@v2
      with:
        image: azure-pipelines-centos7
        tags: ${{ github.sha }}
        context: centos7
        dockerfiles: |
          ./centos7/Dockerfile
